# dataset args
task_name : prev_curr_future
data_prefix_in : relabeled_prev_curr_future_upsampled
data_prefix_out: relabeled_second_pass_prev_curr_future_upsampled
classifier_path : /checkpoint/ccross/sweeps/style_controlled_classifier/005/ee0_jobid=1/model
report_dir : /checkpoint/ccross/sweeps/style_controlled_classifier/005/ee0_jobid=1/reports

# classifier args
batch_size : 256
relabeling_threshold : 0.75
exclude_from_eval : [style_gen, wow, convai2] # since these come from bots
output_file_prefix : /checkpoint/ccross/data/empathy_labeled_joint_datasets/binary_labels/relabeled_second_pass
results_file_prefix : /checkpoint/ccross/results/results_two_relabel_prev_curr_future_utt